# This is a basic workflow to help you get started with Action

name: Experiment
on: #[push]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
    - name: Sleep and Run
      run: |
        echo "Sleeping for 10"
        sleep 10

  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Dependant is Running
      run: |
        echo "Completed job 2 "
       

  job3:
    name: Job 3
    needs: job2
    runs-on: ubuntu-latest

    steps:
    - name: job 3 will run after remove exit 1  from job 2
      run: |
        echo "If you can read this, the experiment failed"

  
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
